export const campaignWriteAbi = [
  {
    type: "function",
    name: "contribute",
    stateMutability: "nonpayable",
    inputs: [{ name: "requestedAmount", type: "uint256" }],
    outputs: [{ name: "acceptedAmount", type: "uint256" }],
  },
  { type: "function", name: "activateFundingFailure", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "submitMilestoneEvidence",
    stateMutability: "nonpayable",
    inputs: [
      { name: "index", type: "uint256" },
      { name: "evidenceURI", type: "string" },
      { name: "evidenceHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "voteMilestone",
    stateMutability: "nonpayable",
    inputs: [{ name: "index", type: "uint256" }, { name: "choice", type: "uint8" }],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeMilestone",
    stateMutability: "nonpayable",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "resolveDispute",
    stateMutability: "nonpayable",
    inputs: [{ name: "index", type: "uint256" }, { name: "approve", type: "bool" }],
    outputs: [],
  },
  {
    type: "function",
    name: "expireDispute",
    stateMutability: "nonpayable",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [],
  },
  { type: "function", name: "cancelForMissingMilestone", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "refund", stateMutability: "nonpayable", inputs: [], outputs: [{ name: "amount", type: "uint256" }] },
] as const;
